services:
  mariadb:
    container_name: mariadb
    networks:
    - inception-network
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
    - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
    - "3306"
  wordpress:
    container_name: wordpress
    networks:
    - inception-network
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
    - wordpress:/var/www/html/wordpress
    restart: on-failure
    expose:
    - "9000"
  nginx:
    container_name: nginx
    networks:
    - inception-network
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
    - wordpress:/var/www/html/wordpress
    restart: on-failure
    ports:
    - "443:443"

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/vvalet/data/mariadb'
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/vvalet/data/wordpress'

networks:
  inception-network:
    driver: bridge
